name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clear cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
            # ^ This key should match the key used when caching npm dependencies
          restore-keys: |
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

