name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code without submodules
        uses: actions/checkout@v2
        with:
          submodules: false
      
      # Add your build and test steps here
